### ISSUE TITLE
Enhance to process args as individual records (vs preprocessed args injected by .NET) 

### ISSUE THREAD

**Issue by codelovercc** [raerae1616/CommandLineArgsHelper#2]
Here's my code.
```C#
       var args = new[]
        {
            "-size=100",
            "/height:'400'",
            "/day:\"happy birthday\"",
            "-tgif=\"Thank God It's Friday\"",
            "-AmINice \"Nice stuff !\"",
            "--debug",
            "-param1 value1",
            "--param2Alone",
            "/param3:\"Test-:-work\"",
            "/param4=--value4--",
            "-param5 \"--=nice=--\"",
            "/\"param6 with spaces\"=\"Spaces are A-OK!\""
        };
        var dic2 = new CommandLineArgsHelpers.CommandLineArgsHelper(args);
        _testOutputHelper.WriteLine(dic2.Parameters.Select(pair => $"argName: {pair.Key}\nargValue: {pair.Value}")
            .Aggregate((s, s1) => $"{s}\n----------------------------------\n{s1}"));
```
and with result:
```Console
argName: size
argValue: 100
----------------------------------
argName: height
argValue: 400
----------------------------------
argName: day
argValue: happy birthday
----------------------------------
argName: tgif
argValue: Thank God It's Friday
----------------------------------
argName: AmINice "Nice stuff !"
argValue: true
----------------------------------
argName: debug
argValue: true
----------------------------------
argName: param1 value1
argValue: true
----------------------------------
argName: param3
argValue: Test-:-work
----------------------------------
argName: param2Alone
argValue: true
----------------------------------
argName: param4
argValue: --value4--
----------------------------------
argName: param5 "--
argValue: nice=--
----------------------------------
argName: "param6 with spaces"
argValue: Spaces are A-OK!

```

Do you see the value of the arg AmINice and param5 ? The values are not correct.

**Comment by codelovercc** [comment]
I've updated regex of SplitterRegex.
```Regex
^-{1,2}|^\/|=|:|\s+"
```
Now, the AmINice's value is correct and param5 also.

**Comment by codelovercc** [comment]
solved!
```C#
using System.Text.RegularExpressions;

namespace CommandLineArgsHelper;

public static class CommandLineArgsHelper
{
    private static readonly Regex SplitterRegex =
        new("^-{1,2}|^\\/|=|:|\\s+\"", RegexOptions.IgnoreCase | RegexOptions.Compiled);

    private static readonly Regex CleanerRegex =
        new("^['\"]?(.*?)['\"]?$", RegexOptions.IgnoreCase | RegexOptions.Compiled);

    public static IDictionary<string, string> ParseArgumentsHelper(string[]? argsArray)
    {
        var paramDictionary = new Dictionary<string, string>();
        if (argsArray == null || argsArray.Length == 0)
            return paramDictionary;
        string? parameter = null;
        foreach (var args in argsArray)
        {
            var strArray = SplitterRegex.Split(args, 3);
            switch (strArray.Length)
            {
                case 1:
                    TryInitParamInDictionary(paramDictionary, parameter, strArray[0]);
                    parameter = null;
                    break;
                case 2:
                    TryInitParamInDictionary(paramDictionary, parameter);
                    parameter = strArray[1];
                    break;
                case 3:
                    if (!TryInitParamInDictionary(paramDictionary, strArray[1], strArray[2]))
                        TryInitParamInDictionary(paramDictionary, parameter, args);
                    else
                        TryInitParamInDictionary(paramDictionary, parameter);
                    parameter = null;
                    break;
            }
        }

        TryInitParamInDictionary(paramDictionary, parameter);
        return paramDictionary;
    }

    private static bool TryInitParamInDictionary(
        IDictionary<string, string> paramDictionary,
        string? parameter,
        string value = "true")
    {
        if (string.IsNullOrEmpty(parameter) || paramDictionary.ContainsKey(parameter))
            return false;
        var str = CleanerRegex.Replace(value, "$1");
        paramDictionary.Add(parameter, str);
        return true;
    }
}
```

**Comment by cajuncoding** [comment]
I’ll take a look in the next few days, but if you have it resolved then I’m happy to review a Pull Request   👍

**Comment by codelovercc** [comment]
Please review the Pull Request that I just created. Thanks.

**Comment by codelovercc** [comment]
Please review the Pull Request that I just created. Thanks.

**Comment by cajuncoding** [comment]
Ok, so looking into this a bit more this is **not a bug.**  The mock args you are trying to use deviate from what .NET injects into a Main() method (which I believe is parsed by Windows API).... so that would explain why it's not working as expected and as the sample Console App shows when you run it.

As can be seen in Visual Studio, the arguments are pre-processed by a lexer  -- e.g. there are no longer any double-quotes `"` embedded in the values, they are parsed out, and some keys are broken into multiple entries, etc. 

![image](https://user-images.githubusercontent.com/20844814/181830497-42bb57cc-0820-43c5-86e7-7dc95fb1b9ff.png)

**Comment by cajuncoding** [comment]
I do see an actual bug with the `--debug` parameter not parsing due to a newline character (from the way it's set in the Startup properties of the Console App; which it should account for also just to be robust.... 😊

**Comment by cajuncoding** [comment]
Ok, so at the surface this may seem like an easy thing to resolve, but the fix you provided does not handle the example `-param1 value1` correctly.  

![image](https://user-images.githubusercontent.com/20844814/181837796-4f19be12-f308-4854-9c01-2702484b0b4a.png)

And after deep diving into this I've found a fundamental contradiction between your sample code with each param as an array entry vs the way they are injected by .NET after being pre-processed....

I was able to resolve the issue using a Unit Test with your code but that then breaks the processing for values coming from .NET `args` because an attempt to match on spaces from the end of the string fails when the values are already separated into multiple entries... the param `Nice stuff !` (see screenshot above) results in an additional result from the spaces within the value. 

So the solution to supporting the formats you are requesting is quite a bit more complex... and confirms that this isn't a bug, but really a request to support different formats than what is provided by `args` injected into `Main(string[] args)` method by .NET.
